version:  '3.7'

services:
  web:
    platform: linux/x86_64
    container_name: web
    build:
      dockerfile: ./docker/dockerfile/node/Dockerfile
      context: ../
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../:/var/www/app/
      - /var/www/app/node_modules
      - ../package.json:/var/www/app/package.json
