FROM node:20-alpine
RUN apk add g++ make py3-pip

WORKDIR /var/www/app

COPY package*.json ./

RUN npm install
RUN npm ci --only=production
RUN mkdir /var/www/app/node_modules/.cache && chmod -R 777 /var/www/app/node_modules/.cache
COPY . .

EXPOSE 3000

CMD ["npm", "run", "build"]
